// Extension System Types
// See specs/012-extension-system/data-model.md

/** JSON manifest file declaring an extension's capabilities */
export interface ExtensionManifest {
  /** Unique extension identifier (matches folder name, alphanumeric + hyphens) */
  name: string;
  /** Human-readable name for the panel picker */
  displayName: string;
  /** Panel configuration (omit for skill-only extensions) */
  panel?: {
    /** Path to HTML entry point, relative to extension root */
    entry: string;
    /** Preferred panel slot */
    defaultPosition: 'left' | 'right';
    /** Icon name for panel picker */
    icon: string;
  };
  /** Skill directories relative to extension root */
  skills?: string[];
  /** Board command types this extension handles (routed to iframe) */
  boardCommands?: string[];
}

/** Runtime representation of a discovered and validated extension */
export interface LoadedExtension {
  /** Extension name from manifest */
  name: string;
  /** Display name from manifest */
  displayName: string;
  /** Resolved URL to the extension's HTML entry point (null for skill-only) */
  panelUrl: string | null;
  /** Panel configuration from manifest */
  panelConfig: {
    defaultPosition: 'left' | 'right';
    icon: string;
  } | null;
  /** Board command types this extension handles */
  boardCommands: string[];
  /** Panel content key: `ext:<name>` */
  panelKey: string;
}

/** Host → Extension messages */
export type HostToExtensionMessage =
  | { type: 'init'; sessionId: string; extensionName: string }
  | { type: 'board-command'; command: string; params: Record<string, string> };

/** Extension → Host messages */
export type ExtensionToHostMessage =
  | { type: 'ready' }
  | { type: 'board-command'; command: string; params: Record<string, string> }
  | { type: 'send-comment'; text: string; context: Record<string, string> };

/** Union of all postMessage payloads */
export type PostMessagePayload = HostToExtensionMessage | ExtensionToHostMessage;

/** Extension index file generated by Vite plugin */
export interface ExtensionIndex {
  extensions: string[];
}
